server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-Zone: http://${eureka.instance.hostname}:${server.port}/${spring.application.name}/